name: Build and Publish Docker Image

on:
  push:
    branches: [main]
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: sirosfoundation/.github/.github/workflows/docker-build-push.yml@8b079d7f8fa866a3406d1f414e740cc51b8f35f1 # main
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      image-name: sirosfoundation/go-invite-op
